// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ad_lego_overpass.proto

package ad_lego_overpass

import (
	ad_base_overpass "github.com/zbwang163/ad_base_overpass"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte                        `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Base  *ad_base_overpass.BaseRequest `protobuf:"bytes,15,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_lego_overpass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_lego_overpass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_ad_lego_overpass_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *UploadImageRequest) GetBase() *ad_base_overpass.BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type UploadImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UploadImageResponse_UploadImageData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Base *ad_base_overpass.BaseResponse       `protobuf:"bytes,15,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_lego_overpass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_lego_overpass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_ad_lego_overpass_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageResponse) GetData() *UploadImageResponse_UploadImageData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageResponse) GetBase() *ad_base_overpass.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UploadImageResponse_UploadImageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *UploadImageResponse_UploadImageData) Reset() {
	*x = UploadImageResponse_UploadImageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_lego_overpass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageResponse_UploadImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse_UploadImageData) ProtoMessage() {}

func (x *UploadImageResponse_UploadImageData) ProtoReflect() protoreflect.Message {
	mi := &file_ad_lego_overpass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse_UploadImageData.ProtoReflect.Descriptor instead.
func (*UploadImageResponse_UploadImageData) Descriptor() ([]byte, []int) {
	return file_ad_lego_overpass_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UploadImageResponse_UploadImageData) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_ad_lego_overpass_proto protoreflect.FileDescriptor

var file_ad_lego_overpass_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x6f, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4c, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0xa2,
	0x01, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x1a, 0x2e, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x32, 0x49, 0x0a, 0x0b, 0x4c, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x13, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x62, 0x77,
	0x61, 0x6e, 0x67, 0x31, 0x36, 0x33, 0x2f, 0x61, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x6f, 0x5f, 0x6f,
	0x76, 0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ad_lego_overpass_proto_rawDescOnce sync.Once
	file_ad_lego_overpass_proto_rawDescData = file_ad_lego_overpass_proto_rawDesc
)

func file_ad_lego_overpass_proto_rawDescGZIP() []byte {
	file_ad_lego_overpass_proto_rawDescOnce.Do(func() {
		file_ad_lego_overpass_proto_rawDescData = protoimpl.X.CompressGZIP(file_ad_lego_overpass_proto_rawDescData)
	})
	return file_ad_lego_overpass_proto_rawDescData
}

var file_ad_lego_overpass_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ad_lego_overpass_proto_goTypes = []interface{}{
	(*UploadImageRequest)(nil),                  // 0: UploadImageRequest
	(*UploadImageResponse)(nil),                 // 1: UploadImageResponse
	(*UploadImageResponse_UploadImageData)(nil), // 2: UploadImageResponse.UploadImageData
	(*ad_base_overpass.BaseRequest)(nil),        // 3: BaseRequest
	(*ad_base_overpass.BaseResponse)(nil),       // 4: BaseResponse
}
var file_ad_lego_overpass_proto_depIdxs = []int32{
	3, // 0: UploadImageRequest.base:type_name -> BaseRequest
	2, // 1: UploadImageResponse.data:type_name -> UploadImageResponse.UploadImageData
	4, // 2: UploadImageResponse.base:type_name -> BaseResponse
	0, // 3: LegoService.UploadImage:input_type -> UploadImageRequest
	1, // 4: LegoService.UploadImage:output_type -> UploadImageResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ad_lego_overpass_proto_init() }
func file_ad_lego_overpass_proto_init() {
	if File_ad_lego_overpass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ad_lego_overpass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_lego_overpass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_lego_overpass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageResponse_UploadImageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ad_lego_overpass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ad_lego_overpass_proto_goTypes,
		DependencyIndexes: file_ad_lego_overpass_proto_depIdxs,
		MessageInfos:      file_ad_lego_overpass_proto_msgTypes,
	}.Build()
	File_ad_lego_overpass_proto = out.File
	file_ad_lego_overpass_proto_rawDesc = nil
	file_ad_lego_overpass_proto_goTypes = nil
	file_ad_lego_overpass_proto_depIdxs = nil
}
